# Generated by Django 4.2.6 on 2023-10-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100)),
                ("amount", models.IntegerField(help_text="in cents")),
                ("currency", models.CharField(choices=[("eur", "Eur")], max_length=20)),
                ("date", models.DateField()),
                (
                    "description",
                    models.CharField(
                        choices=[("sepa", "SEPA-domiciliëring")], max_length=100
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "account_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_from",
                        to="expense_tracker.account",
                    ),
                ),
                (
                    "account_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_to",
                        to="expense_tracker.account",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="expense_tracker.organization",
            ),
        ),
    ]
