# Generated by Django 4.2.6 on 2023-10-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expense_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="expense_tracker.organization",
            ),
        ),
    ]
