# Generated by Django 4.2.6 on 2023-10-11 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expense_tracker", "0003_alter_account_number_alter_organization_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer",
            name="account_from",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="account_to",
        ),
        migrations.AddField(
            model_name="transfer",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="expense_tracker.account",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transfer",
            name="recipient",
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
