# Generated by Django 4.2.6 on 2023-10-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_tracker", "0004_remove_transfer_account_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="account",
            field=models.CharField(max_length=100),
        ),
    ]
