# Generated by Django 4.2.6 on 2023-10-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expense_tracker", "0005_alter_transfer_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer",
            name="description",
        ),
        migrations.AlterField(
            model_name="account",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="expense_tracker.organization",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="expense_tracker.account",
            ),
        ),
    ]
